// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2-eq5Zrnp2n7aBB6-6_bjVJvqr89nZ8',
    appId: '1:68722970471:web:7c70b07c6bec178212e9c2',
    messagingSenderId: '68722970471',
    projectId: 'zagorito-9a0c4',
    authDomain: 'zagorito-9a0c4.firebaseapp.com',
    storageBucket: 'zagorito-9a0c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAHMRUEEeVEJhKSjSt6wMeYpo2xpbkLjk',
    appId: '1:68722970471:android:22dce79885650fc112e9c2',
    messagingSenderId: '68722970471',
    projectId: 'zagorito-9a0c4',
    storageBucket: 'zagorito-9a0c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw1pC6Pe1sEr1Cq_j6SG2akCFtihzwyK8',
    appId: '1:68722970471:ios:69befe61397a785b12e9c2',
    messagingSenderId: '68722970471',
    projectId: 'zagorito-9a0c4',
    storageBucket: 'zagorito-9a0c4.firebasestorage.app',
    iosBundleId: 'com.zagorito.boosterfish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw1pC6Pe1sEr1Cq_j6SG2akCFtihzwyK8',
    appId: '1:68722970471:ios:69befe61397a785b12e9c2',
    messagingSenderId: '68722970471',
    projectId: 'zagorito-9a0c4',
    storageBucket: 'zagorito-9a0c4.firebasestorage.app',
    iosBundleId: 'com.zagorito.boosterfish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2-eq5Zrnp2n7aBB6-6_bjVJvqr89nZ8',
    appId: '1:68722970471:web:33840a06f8c3f12b12e9c2',
    messagingSenderId: '68722970471',
    projectId: 'zagorito-9a0c4',
    authDomain: 'zagorito-9a0c4.firebaseapp.com',
    storageBucket: 'zagorito-9a0c4.firebasestorage.app',
  );
}
